overrides: "git://github.com/pyexcel/pyexcel-mobans!/mobanfile.yaml"
configuration:
  configuration: pyexcel-xlsx.yml
targets:
  - Pipfile: Pipfile.jj2
  - README.rst: custom_README.rst.jj2
  - setup.py: setup.py
  - "docs/source/conf.py": "docs/source/conf.py.jj2"
  - .travis.yml: travis.yml
  - MANIFEST.in: MANIFEST.in.jj2
  - .gitignore: gitignore.jj2
  - "tests/requirements.txt": "tests/requirements.txt"
  - "tests/test_filter.py": "tests/test_filter.py.jj2"
  - "tests/test_formatters.py": "tests/test_formatters.py"
  - "tests/test_stringio.py": "tests/test_stringio.py.jj2"
  - "tests/test_writer.py": "tests/test_writer.py.jj2"
  - "tests/base.py": "tests/base.py"
